<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  
    <ApplicationManifest>app.manifest</ApplicationManifest>
	  
    <AssemblyName>electriCad</AssemblyName>
	  
    <ApplicationIcon>electrical-storm-weather-symbol-of-black-lightning-bolt-shape_icon-icons.com_64228.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="App.config" />
    <None Remove="Cables\cablesSpecs.json" />
    <None Remove="database\cables.json" />
    <None Remove="database\conduitsSizes.json" />
    <None Remove="installation_details.png" />
    <None Remove="Projects\add.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Cables\cablesSpecs.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="database\cables.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="database\conduitsSizes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="electrical-storm-weather-symbol-of-black-lightning-bolt-shape_icon-icons.com_64228.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.0.5" />
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignExtensions" Version="3.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="5.2.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CableCalculator">
      <HintPath>..\..\..\..\..\..\Temp\cable calculator new\CableCalculator.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="installation_details.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Projects\add.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="arrowGIF.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Conduits\CircuitsUpload.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ED8\motor_specifications.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="elec.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
