<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="App.config" />
    <None Remove="database\cables.json" />
    <None Remove="database\conduitsSizes.json" />
    <None Remove="Projects\add.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="database\cables.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="database\conduitsSizes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.0.5" />
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignExtensions" Version="3.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="5.2.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CableCalculator">
      <HintPath>..\..\..\..\Downloads\CableCalculator.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Projects\add.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="arrowGIF.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Conduits\CircuitsUpload.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
